name: "CodeQL analysis"

on: 
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  codeql:

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest # you can try windows too but macos is not yet supported

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive # omit this if your repository doesn't use submodules
    - uses: Anthophila/codeql-action/codeql/init@master
    - uses: Anthophila/codeql-action/codeql/finish@master
